// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShooterProtocol.proto

#include "ShooterProtocol.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Shooter {
PROTOBUF_CONSTEXPR PVector::PVector(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.x_)*/0
  , /*decltype(_impl_.y_)*/0
  , /*decltype(_impl_.z_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PVectorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PVectorDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PVectorDefaultTypeInternal() {}
  union {
    PVector _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PVectorDefaultTypeInternal _PVector_default_instance_;
PROTOBUF_CONSTEXPR PRotator::PRotator(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.roll_)*/0
  , /*decltype(_impl_.pitch_)*/0
  , /*decltype(_impl_.yaw_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PRotatorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PRotatorDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PRotatorDefaultTypeInternal() {}
  union {
    PRotator _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PRotatorDefaultTypeInternal _PRotator_default_instance_;
PROTOBUF_CONSTEXPR PWeapon::PWeapon(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.id_)*/nullptr
  , /*decltype(_impl_.startfire_)*/false
  , /*decltype(_impl_.stopfire_)*/false
  , /*decltype(_impl_.changenextweapon_)*/false
  , /*decltype(_impl_.changeprevweapon_)*/false
  , /*decltype(_impl_.startreload_)*/false
  , /*decltype(_impl_.ammo_)*/0u
  , /*decltype(_impl_.clipammo_)*/0u} {}
struct PWeaponDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PWeaponDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PWeaponDefaultTypeInternal() {}
  union {
    PWeapon _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PWeaponDefaultTypeInternal _PWeapon_default_instance_;
PROTOBUF_CONSTEXPR PFireEvent::PFireEvent(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.id_)*/nullptr
  , /*decltype(_impl_.aimdir_)*/nullptr
  , /*decltype(_impl_.starttrace_)*/nullptr
  , /*decltype(_impl_.randomseed_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PFireEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PFireEventDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PFireEventDefaultTypeInternal() {}
  union {
    PFireEvent _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PFireEventDefaultTypeInternal _PFireEvent_default_instance_;
PROTOBUF_CONSTEXPR PClientId::PClientId(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.index_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PClientIdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PClientIdDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PClientIdDefaultTypeInternal() {}
  union {
    PClientId _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PClientIdDefaultTypeInternal _PClientId_default_instance_;
PROTOBUF_CONSTEXPR PMovement::PMovement(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.id_)*/nullptr
  , /*decltype(_impl_.loc_)*/nullptr
  , /*decltype(_impl_.rot_)*/nullptr
  , /*decltype(_impl_.vel_)*/nullptr} {}
struct PMovementDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PMovementDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PMovementDefaultTypeInternal() {}
  union {
    PMovement _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PMovementDefaultTypeInternal _PMovement_default_instance_;
PROTOBUF_CONSTEXPR PAnimState::PAnimState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.id_)*/nullptr
  , /*decltype(_impl_.aimyaw_)*/0
  , /*decltype(_impl_.aimpitch_)*/0} {}
struct PAnimStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PAnimStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PAnimStateDefaultTypeInternal() {}
  union {
    PAnimState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PAnimStateDefaultTypeInternal _PAnimState_default_instance_;
}  // namespace Shooter
static ::_pb::Metadata file_level_metadata_ShooterProtocol_2eproto[7];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_ShooterProtocol_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ShooterProtocol_2eproto = nullptr;

const uint32_t TableStruct_ShooterProtocol_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Shooter::PVector, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Shooter::PVector, _impl_.x_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PVector, _impl_.y_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PVector, _impl_.z_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Shooter::PRotator, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Shooter::PRotator, _impl_.roll_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PRotator, _impl_.pitch_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PRotator, _impl_.yaw_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PWeapon, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PWeapon, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Shooter::PWeapon, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PWeapon, _impl_.startfire_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PWeapon, _impl_.stopfire_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PWeapon, _impl_.changenextweapon_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PWeapon, _impl_.changeprevweapon_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PWeapon, _impl_.startreload_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PWeapon, _impl_.ammo_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PWeapon, _impl_.clipammo_),
  ~0u,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Shooter::PFireEvent, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Shooter::PFireEvent, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PFireEvent, _impl_.randomseed_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PFireEvent, _impl_.aimdir_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PFireEvent, _impl_.starttrace_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Shooter::PClientId, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Shooter::PClientId, _impl_.index_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PMovement, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PMovement, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Shooter::PMovement, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PMovement, _impl_.loc_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PMovement, _impl_.rot_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PMovement, _impl_.vel_),
  ~0u,
  0,
  1,
  2,
  PROTOBUF_FIELD_OFFSET(::Shooter::PAnimState, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PAnimState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Shooter::PAnimState, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PAnimState, _impl_.aimyaw_),
  PROTOBUF_FIELD_OFFSET(::Shooter::PAnimState, _impl_.aimpitch_),
  ~0u,
  0,
  1,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Shooter::PVector)},
  { 9, -1, -1, sizeof(::Shooter::PRotator)},
  { 18, 32, -1, sizeof(::Shooter::PWeapon)},
  { 40, -1, -1, sizeof(::Shooter::PFireEvent)},
  { 50, -1, -1, sizeof(::Shooter::PClientId)},
  { 57, 67, -1, sizeof(::Shooter::PMovement)},
  { 71, 80, -1, sizeof(::Shooter::PAnimState)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Shooter::_PVector_default_instance_._instance,
  &::Shooter::_PRotator_default_instance_._instance,
  &::Shooter::_PWeapon_default_instance_._instance,
  &::Shooter::_PFireEvent_default_instance_._instance,
  &::Shooter::_PClientId_default_instance_._instance,
  &::Shooter::_PMovement_default_instance_._instance,
  &::Shooter::_PAnimState_default_instance_._instance,
};

const char descriptor_table_protodef_ShooterProtocol_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025ShooterProtocol.proto\022\007Shooter\"*\n\007PVec"
  "tor\022\t\n\001X\030\001 \001(\002\022\t\n\001Y\030\002 \001(\002\022\t\n\001Z\030\003 \001(\002\"4\n\010"
  "PRotator\022\014\n\004Roll\030\001 \001(\002\022\r\n\005Pitch\030\002 \001(\002\022\013\n"
  "\003Yaw\030\003 \001(\002\"\305\002\n\007PWeapon\022\036\n\002Id\030\001 \001(\0132\022.Sho"
  "oter.PClientId\022\026\n\tStartFire\030\002 \001(\010H\000\210\001\001\022\025"
  "\n\010StopFire\030\003 \001(\010H\001\210\001\001\022\035\n\020ChangeNextWeapo"
  "n\030\004 \001(\010H\002\210\001\001\022\035\n\020ChangePrevWeapon\030\005 \001(\010H\003"
  "\210\001\001\022\030\n\013StartReload\030\006 \001(\010H\004\210\001\001\022\021\n\004Ammo\030\007 "
  "\001(\rH\005\210\001\001\022\025\n\010ClipAmmo\030\010 \001(\rH\006\210\001\001B\014\n\n_Star"
  "tFireB\013\n\t_StopFireB\023\n\021_ChangeNextWeaponB"
  "\023\n\021_ChangePrevWeaponB\016\n\014_StartReloadB\007\n\005"
  "_AmmoB\013\n\t_ClipAmmo\"\210\001\n\nPFireEvent\022\036\n\002Id\030"
  "\001 \001(\0132\022.Shooter.PClientId\022\022\n\nRandomSeed\030"
  "\002 \001(\002\022 \n\006AimDir\030\003 \001(\0132\020.Shooter.PVector\022"
  "$\n\nStartTrace\030\004 \001(\0132\020.Shooter.PVector\"\032\n"
  "\tPClientId\022\r\n\005Index\030\001 \001(\r\"\260\001\n\tPMovement\022"
  "\036\n\002Id\030\001 \001(\0132\022.Shooter.PClientId\022\"\n\003Loc\030\002"
  " \001(\0132\020.Shooter.PVectorH\000\210\001\001\022#\n\003Rot\030\003 \001(\013"
  "2\021.Shooter.PRotatorH\001\210\001\001\022\"\n\003Vel\030\004 \001(\0132\020."
  "Shooter.PVectorH\002\210\001\001B\006\n\004_LocB\006\n\004_RotB\006\n\004"
  "_Vel\"p\n\nPAnimState\022\036\n\002Id\030\001 \001(\0132\022.Shooter"
  ".PClientId\022\023\n\006AimYaw\030\002 \001(\002H\000\210\001\001\022\025\n\010AimPi"
  "tch\030\003 \001(\002H\001\210\001\001B\t\n\007_AimYawB\013\n\t_AimPitchb\006"
  "proto3"
  ;
static ::_pbi::once_flag descriptor_table_ShooterProtocol_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ShooterProtocol_2eproto = {
    false, false, 926, descriptor_table_protodef_ShooterProtocol_2eproto,
    "ShooterProtocol.proto",
    &descriptor_table_ShooterProtocol_2eproto_once, nullptr, 0, 7,
    schemas, file_default_instances, TableStruct_ShooterProtocol_2eproto::offsets,
    file_level_metadata_ShooterProtocol_2eproto, file_level_enum_descriptors_ShooterProtocol_2eproto,
    file_level_service_descriptors_ShooterProtocol_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ShooterProtocol_2eproto_getter() {
  return &descriptor_table_ShooterProtocol_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ShooterProtocol_2eproto(&descriptor_table_ShooterProtocol_2eproto);
namespace Shooter {

// ===================================================================

class PVector::_Internal {
 public:
};

PVector::PVector(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Shooter.PVector)
}
PVector::PVector(const PVector& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PVector* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){}
    , decltype(_impl_.y_){}
    , decltype(_impl_.z_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.x_, &from._impl_.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.z_) -
    reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.z_));
  // @@protoc_insertion_point(copy_constructor:Shooter.PVector)
}

inline void PVector::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){0}
    , decltype(_impl_.y_){0}
    , decltype(_impl_.z_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PVector::~PVector() {
  // @@protoc_insertion_point(destructor:Shooter.PVector)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PVector::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PVector::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PVector::Clear() {
// @@protoc_insertion_point(message_clear_start:Shooter.PVector)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.z_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.z_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PVector::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float X = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float Y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float Z = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _impl_.z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PVector::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Shooter.PVector)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float X = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_x(), target);
  }

  // float Y = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_y(), target);
  }

  // float Z = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_z(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Shooter.PVector)
  return target;
}

size_t PVector::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Shooter.PVector)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float X = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    total_size += 1 + 4;
  }

  // float Y = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    total_size += 1 + 4;
  }

  // float Z = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PVector::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PVector::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PVector::GetClassData() const { return &_class_data_; }


void PVector::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PVector*>(&to_msg);
  auto& from = static_cast<const PVector&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Shooter.PVector)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = from._internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = from._internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_z = from._internal_z();
  uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    _this->_internal_set_z(from._internal_z());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PVector::CopyFrom(const PVector& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Shooter.PVector)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PVector::IsInitialized() const {
  return true;
}

void PVector::InternalSwap(PVector* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PVector, _impl_.z_)
      + sizeof(PVector::_impl_.z_)
      - PROTOBUF_FIELD_OFFSET(PVector, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PVector::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ShooterProtocol_2eproto_getter, &descriptor_table_ShooterProtocol_2eproto_once,
      file_level_metadata_ShooterProtocol_2eproto[0]);
}

// ===================================================================

class PRotator::_Internal {
 public:
};

PRotator::PRotator(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Shooter.PRotator)
}
PRotator::PRotator(const PRotator& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PRotator* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.roll_){}
    , decltype(_impl_.pitch_){}
    , decltype(_impl_.yaw_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.roll_, &from._impl_.roll_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.yaw_) -
    reinterpret_cast<char*>(&_impl_.roll_)) + sizeof(_impl_.yaw_));
  // @@protoc_insertion_point(copy_constructor:Shooter.PRotator)
}

inline void PRotator::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.roll_){0}
    , decltype(_impl_.pitch_){0}
    , decltype(_impl_.yaw_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PRotator::~PRotator() {
  // @@protoc_insertion_point(destructor:Shooter.PRotator)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PRotator::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PRotator::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PRotator::Clear() {
// @@protoc_insertion_point(message_clear_start:Shooter.PRotator)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.roll_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.yaw_) -
      reinterpret_cast<char*>(&_impl_.roll_)) + sizeof(_impl_.yaw_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PRotator::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float Roll = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.roll_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float Pitch = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.pitch_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float Yaw = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _impl_.yaw_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PRotator::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Shooter.PRotator)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float Roll = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_roll = this->_internal_roll();
  uint32_t raw_roll;
  memcpy(&raw_roll, &tmp_roll, sizeof(tmp_roll));
  if (raw_roll != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_roll(), target);
  }

  // float Pitch = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_pitch = this->_internal_pitch();
  uint32_t raw_pitch;
  memcpy(&raw_pitch, &tmp_pitch, sizeof(tmp_pitch));
  if (raw_pitch != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_pitch(), target);
  }

  // float Yaw = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_yaw = this->_internal_yaw();
  uint32_t raw_yaw;
  memcpy(&raw_yaw, &tmp_yaw, sizeof(tmp_yaw));
  if (raw_yaw != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_yaw(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Shooter.PRotator)
  return target;
}

size_t PRotator::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Shooter.PRotator)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float Roll = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_roll = this->_internal_roll();
  uint32_t raw_roll;
  memcpy(&raw_roll, &tmp_roll, sizeof(tmp_roll));
  if (raw_roll != 0) {
    total_size += 1 + 4;
  }

  // float Pitch = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_pitch = this->_internal_pitch();
  uint32_t raw_pitch;
  memcpy(&raw_pitch, &tmp_pitch, sizeof(tmp_pitch));
  if (raw_pitch != 0) {
    total_size += 1 + 4;
  }

  // float Yaw = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_yaw = this->_internal_yaw();
  uint32_t raw_yaw;
  memcpy(&raw_yaw, &tmp_yaw, sizeof(tmp_yaw));
  if (raw_yaw != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PRotator::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PRotator::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PRotator::GetClassData() const { return &_class_data_; }


void PRotator::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PRotator*>(&to_msg);
  auto& from = static_cast<const PRotator&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Shooter.PRotator)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_roll = from._internal_roll();
  uint32_t raw_roll;
  memcpy(&raw_roll, &tmp_roll, sizeof(tmp_roll));
  if (raw_roll != 0) {
    _this->_internal_set_roll(from._internal_roll());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_pitch = from._internal_pitch();
  uint32_t raw_pitch;
  memcpy(&raw_pitch, &tmp_pitch, sizeof(tmp_pitch));
  if (raw_pitch != 0) {
    _this->_internal_set_pitch(from._internal_pitch());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_yaw = from._internal_yaw();
  uint32_t raw_yaw;
  memcpy(&raw_yaw, &tmp_yaw, sizeof(tmp_yaw));
  if (raw_yaw != 0) {
    _this->_internal_set_yaw(from._internal_yaw());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PRotator::CopyFrom(const PRotator& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Shooter.PRotator)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PRotator::IsInitialized() const {
  return true;
}

void PRotator::InternalSwap(PRotator* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PRotator, _impl_.yaw_)
      + sizeof(PRotator::_impl_.yaw_)
      - PROTOBUF_FIELD_OFFSET(PRotator, _impl_.roll_)>(
          reinterpret_cast<char*>(&_impl_.roll_),
          reinterpret_cast<char*>(&other->_impl_.roll_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PRotator::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ShooterProtocol_2eproto_getter, &descriptor_table_ShooterProtocol_2eproto_once,
      file_level_metadata_ShooterProtocol_2eproto[1]);
}

// ===================================================================

class PWeapon::_Internal {
 public:
  using HasBits = decltype(std::declval<PWeapon>()._impl_._has_bits_);
  static const ::Shooter::PClientId& id(const PWeapon* msg);
  static void set_has_startfire(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_stopfire(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_changenextweapon(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_changeprevweapon(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_startreload(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_ammo(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_clipammo(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
};

const ::Shooter::PClientId&
PWeapon::_Internal::id(const PWeapon* msg) {
  return *msg->_impl_.id_;
}
PWeapon::PWeapon(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Shooter.PWeapon)
}
PWeapon::PWeapon(const PWeapon& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PWeapon* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.id_){nullptr}
    , decltype(_impl_.startfire_){}
    , decltype(_impl_.stopfire_){}
    , decltype(_impl_.changenextweapon_){}
    , decltype(_impl_.changeprevweapon_){}
    , decltype(_impl_.startreload_){}
    , decltype(_impl_.ammo_){}
    , decltype(_impl_.clipammo_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_id()) {
    _this->_impl_.id_ = new ::Shooter::PClientId(*from._impl_.id_);
  }
  ::memcpy(&_impl_.startfire_, &from._impl_.startfire_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.clipammo_) -
    reinterpret_cast<char*>(&_impl_.startfire_)) + sizeof(_impl_.clipammo_));
  // @@protoc_insertion_point(copy_constructor:Shooter.PWeapon)
}

inline void PWeapon::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.id_){nullptr}
    , decltype(_impl_.startfire_){false}
    , decltype(_impl_.stopfire_){false}
    , decltype(_impl_.changenextweapon_){false}
    , decltype(_impl_.changeprevweapon_){false}
    , decltype(_impl_.startreload_){false}
    , decltype(_impl_.ammo_){0u}
    , decltype(_impl_.clipammo_){0u}
  };
}

PWeapon::~PWeapon() {
  // @@protoc_insertion_point(destructor:Shooter.PWeapon)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PWeapon::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.id_;
}

void PWeapon::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PWeapon::Clear() {
// @@protoc_insertion_point(message_clear_start:Shooter.PWeapon)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.id_ != nullptr) {
    delete _impl_.id_;
  }
  _impl_.id_ = nullptr;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    ::memset(&_impl_.startfire_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.clipammo_) -
        reinterpret_cast<char*>(&_impl_.startfire_)) + sizeof(_impl_.clipammo_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PWeapon::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Shooter.PClientId Id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_id(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool StartFire = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_startfire(&has_bits);
          _impl_.startfire_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool StopFire = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _Internal::set_has_stopfire(&has_bits);
          _impl_.stopfire_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool ChangeNextWeapon = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _Internal::set_has_changenextweapon(&has_bits);
          _impl_.changenextweapon_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool ChangePrevWeapon = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _Internal::set_has_changeprevweapon(&has_bits);
          _impl_.changeprevweapon_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool StartReload = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _Internal::set_has_startreload(&has_bits);
          _impl_.startreload_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 Ammo = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _Internal::set_has_ammo(&has_bits);
          _impl_.ammo_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 ClipAmmo = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _Internal::set_has_clipammo(&has_bits);
          _impl_.clipammo_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PWeapon::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Shooter.PWeapon)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Shooter.PClientId Id = 1;
  if (this->_internal_has_id()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::id(this),
        _Internal::id(this).GetCachedSize(), target, stream);
  }

  // optional bool StartFire = 2;
  if (_internal_has_startfire()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_startfire(), target);
  }

  // optional bool StopFire = 3;
  if (_internal_has_stopfire()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_stopfire(), target);
  }

  // optional bool ChangeNextWeapon = 4;
  if (_internal_has_changenextweapon()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_changenextweapon(), target);
  }

  // optional bool ChangePrevWeapon = 5;
  if (_internal_has_changeprevweapon()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(5, this->_internal_changeprevweapon(), target);
  }

  // optional bool StartReload = 6;
  if (_internal_has_startreload()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(6, this->_internal_startreload(), target);
  }

  // optional uint32 Ammo = 7;
  if (_internal_has_ammo()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(7, this->_internal_ammo(), target);
  }

  // optional uint32 ClipAmmo = 8;
  if (_internal_has_clipammo()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(8, this->_internal_clipammo(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Shooter.PWeapon)
  return target;
}

size_t PWeapon::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Shooter.PWeapon)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Shooter.PClientId Id = 1;
  if (this->_internal_has_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.id_);
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    // optional bool StartFire = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 1;
    }

    // optional bool StopFire = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 1;
    }

    // optional bool ChangeNextWeapon = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 1;
    }

    // optional bool ChangePrevWeapon = 5;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 1;
    }

    // optional bool StartReload = 6;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 1;
    }

    // optional uint32 Ammo = 7;
    if (cached_has_bits & 0x00000020u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_ammo());
    }

    // optional uint32 ClipAmmo = 8;
    if (cached_has_bits & 0x00000040u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_clipammo());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PWeapon::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PWeapon::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PWeapon::GetClassData() const { return &_class_data_; }


void PWeapon::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PWeapon*>(&to_msg);
  auto& from = static_cast<const PWeapon&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Shooter.PWeapon)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_id()) {
    _this->_internal_mutable_id()->::Shooter::PClientId::MergeFrom(
        from._internal_id());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.startfire_ = from._impl_.startfire_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.stopfire_ = from._impl_.stopfire_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.changenextweapon_ = from._impl_.changenextweapon_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.changeprevweapon_ = from._impl_.changeprevweapon_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.startreload_ = from._impl_.startreload_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.ammo_ = from._impl_.ammo_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.clipammo_ = from._impl_.clipammo_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PWeapon::CopyFrom(const PWeapon& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Shooter.PWeapon)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PWeapon::IsInitialized() const {
  return true;
}

void PWeapon::InternalSwap(PWeapon* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PWeapon, _impl_.clipammo_)
      + sizeof(PWeapon::_impl_.clipammo_)
      - PROTOBUF_FIELD_OFFSET(PWeapon, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PWeapon::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ShooterProtocol_2eproto_getter, &descriptor_table_ShooterProtocol_2eproto_once,
      file_level_metadata_ShooterProtocol_2eproto[2]);
}

// ===================================================================

class PFireEvent::_Internal {
 public:
  static const ::Shooter::PClientId& id(const PFireEvent* msg);
  static const ::Shooter::PVector& aimdir(const PFireEvent* msg);
  static const ::Shooter::PVector& starttrace(const PFireEvent* msg);
};

const ::Shooter::PClientId&
PFireEvent::_Internal::id(const PFireEvent* msg) {
  return *msg->_impl_.id_;
}
const ::Shooter::PVector&
PFireEvent::_Internal::aimdir(const PFireEvent* msg) {
  return *msg->_impl_.aimdir_;
}
const ::Shooter::PVector&
PFireEvent::_Internal::starttrace(const PFireEvent* msg) {
  return *msg->_impl_.starttrace_;
}
PFireEvent::PFireEvent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Shooter.PFireEvent)
}
PFireEvent::PFireEvent(const PFireEvent& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PFireEvent* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.id_){nullptr}
    , decltype(_impl_.aimdir_){nullptr}
    , decltype(_impl_.starttrace_){nullptr}
    , decltype(_impl_.randomseed_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_id()) {
    _this->_impl_.id_ = new ::Shooter::PClientId(*from._impl_.id_);
  }
  if (from._internal_has_aimdir()) {
    _this->_impl_.aimdir_ = new ::Shooter::PVector(*from._impl_.aimdir_);
  }
  if (from._internal_has_starttrace()) {
    _this->_impl_.starttrace_ = new ::Shooter::PVector(*from._impl_.starttrace_);
  }
  _this->_impl_.randomseed_ = from._impl_.randomseed_;
  // @@protoc_insertion_point(copy_constructor:Shooter.PFireEvent)
}

inline void PFireEvent::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.id_){nullptr}
    , decltype(_impl_.aimdir_){nullptr}
    , decltype(_impl_.starttrace_){nullptr}
    , decltype(_impl_.randomseed_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PFireEvent::~PFireEvent() {
  // @@protoc_insertion_point(destructor:Shooter.PFireEvent)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PFireEvent::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.id_;
  if (this != internal_default_instance()) delete _impl_.aimdir_;
  if (this != internal_default_instance()) delete _impl_.starttrace_;
}

void PFireEvent::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PFireEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:Shooter.PFireEvent)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.id_ != nullptr) {
    delete _impl_.id_;
  }
  _impl_.id_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.aimdir_ != nullptr) {
    delete _impl_.aimdir_;
  }
  _impl_.aimdir_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.starttrace_ != nullptr) {
    delete _impl_.starttrace_;
  }
  _impl_.starttrace_ = nullptr;
  _impl_.randomseed_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PFireEvent::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Shooter.PClientId Id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_id(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float RandomSeed = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.randomseed_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // .Shooter.PVector AimDir = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_aimdir(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Shooter.PVector StartTrace = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_starttrace(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PFireEvent::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Shooter.PFireEvent)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Shooter.PClientId Id = 1;
  if (this->_internal_has_id()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::id(this),
        _Internal::id(this).GetCachedSize(), target, stream);
  }

  // float RandomSeed = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_randomseed = this->_internal_randomseed();
  uint32_t raw_randomseed;
  memcpy(&raw_randomseed, &tmp_randomseed, sizeof(tmp_randomseed));
  if (raw_randomseed != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_randomseed(), target);
  }

  // .Shooter.PVector AimDir = 3;
  if (this->_internal_has_aimdir()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::aimdir(this),
        _Internal::aimdir(this).GetCachedSize(), target, stream);
  }

  // .Shooter.PVector StartTrace = 4;
  if (this->_internal_has_starttrace()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::starttrace(this),
        _Internal::starttrace(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Shooter.PFireEvent)
  return target;
}

size_t PFireEvent::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Shooter.PFireEvent)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Shooter.PClientId Id = 1;
  if (this->_internal_has_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.id_);
  }

  // .Shooter.PVector AimDir = 3;
  if (this->_internal_has_aimdir()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.aimdir_);
  }

  // .Shooter.PVector StartTrace = 4;
  if (this->_internal_has_starttrace()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.starttrace_);
  }

  // float RandomSeed = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_randomseed = this->_internal_randomseed();
  uint32_t raw_randomseed;
  memcpy(&raw_randomseed, &tmp_randomseed, sizeof(tmp_randomseed));
  if (raw_randomseed != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PFireEvent::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PFireEvent::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PFireEvent::GetClassData() const { return &_class_data_; }


void PFireEvent::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PFireEvent*>(&to_msg);
  auto& from = static_cast<const PFireEvent&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Shooter.PFireEvent)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_id()) {
    _this->_internal_mutable_id()->::Shooter::PClientId::MergeFrom(
        from._internal_id());
  }
  if (from._internal_has_aimdir()) {
    _this->_internal_mutable_aimdir()->::Shooter::PVector::MergeFrom(
        from._internal_aimdir());
  }
  if (from._internal_has_starttrace()) {
    _this->_internal_mutable_starttrace()->::Shooter::PVector::MergeFrom(
        from._internal_starttrace());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_randomseed = from._internal_randomseed();
  uint32_t raw_randomseed;
  memcpy(&raw_randomseed, &tmp_randomseed, sizeof(tmp_randomseed));
  if (raw_randomseed != 0) {
    _this->_internal_set_randomseed(from._internal_randomseed());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PFireEvent::CopyFrom(const PFireEvent& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Shooter.PFireEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PFireEvent::IsInitialized() const {
  return true;
}

void PFireEvent::InternalSwap(PFireEvent* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PFireEvent, _impl_.randomseed_)
      + sizeof(PFireEvent::_impl_.randomseed_)
      - PROTOBUF_FIELD_OFFSET(PFireEvent, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PFireEvent::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ShooterProtocol_2eproto_getter, &descriptor_table_ShooterProtocol_2eproto_once,
      file_level_metadata_ShooterProtocol_2eproto[3]);
}

// ===================================================================

class PClientId::_Internal {
 public:
};

PClientId::PClientId(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Shooter.PClientId)
}
PClientId::PClientId(const PClientId& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PClientId* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.index_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.index_ = from._impl_.index_;
  // @@protoc_insertion_point(copy_constructor:Shooter.PClientId)
}

inline void PClientId::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.index_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PClientId::~PClientId() {
  // @@protoc_insertion_point(destructor:Shooter.PClientId)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PClientId::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PClientId::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PClientId::Clear() {
// @@protoc_insertion_point(message_clear_start:Shooter.PClientId)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.index_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PClientId::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 Index = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PClientId::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Shooter.PClientId)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 Index = 1;
  if (this->_internal_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_index(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Shooter.PClientId)
  return target;
}

size_t PClientId::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Shooter.PClientId)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 Index = 1;
  if (this->_internal_index() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_index());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PClientId::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PClientId::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PClientId::GetClassData() const { return &_class_data_; }


void PClientId::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PClientId*>(&to_msg);
  auto& from = static_cast<const PClientId&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Shooter.PClientId)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_index() != 0) {
    _this->_internal_set_index(from._internal_index());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PClientId::CopyFrom(const PClientId& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Shooter.PClientId)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PClientId::IsInitialized() const {
  return true;
}

void PClientId::InternalSwap(PClientId* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.index_, other->_impl_.index_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PClientId::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ShooterProtocol_2eproto_getter, &descriptor_table_ShooterProtocol_2eproto_once,
      file_level_metadata_ShooterProtocol_2eproto[4]);
}

// ===================================================================

class PMovement::_Internal {
 public:
  using HasBits = decltype(std::declval<PMovement>()._impl_._has_bits_);
  static const ::Shooter::PClientId& id(const PMovement* msg);
  static const ::Shooter::PVector& loc(const PMovement* msg);
  static void set_has_loc(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::Shooter::PRotator& rot(const PMovement* msg);
  static void set_has_rot(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::Shooter::PVector& vel(const PMovement* msg);
  static void set_has_vel(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

const ::Shooter::PClientId&
PMovement::_Internal::id(const PMovement* msg) {
  return *msg->_impl_.id_;
}
const ::Shooter::PVector&
PMovement::_Internal::loc(const PMovement* msg) {
  return *msg->_impl_.loc_;
}
const ::Shooter::PRotator&
PMovement::_Internal::rot(const PMovement* msg) {
  return *msg->_impl_.rot_;
}
const ::Shooter::PVector&
PMovement::_Internal::vel(const PMovement* msg) {
  return *msg->_impl_.vel_;
}
PMovement::PMovement(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Shooter.PMovement)
}
PMovement::PMovement(const PMovement& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PMovement* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.id_){nullptr}
    , decltype(_impl_.loc_){nullptr}
    , decltype(_impl_.rot_){nullptr}
    , decltype(_impl_.vel_){nullptr}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_id()) {
    _this->_impl_.id_ = new ::Shooter::PClientId(*from._impl_.id_);
  }
  if (from._internal_has_loc()) {
    _this->_impl_.loc_ = new ::Shooter::PVector(*from._impl_.loc_);
  }
  if (from._internal_has_rot()) {
    _this->_impl_.rot_ = new ::Shooter::PRotator(*from._impl_.rot_);
  }
  if (from._internal_has_vel()) {
    _this->_impl_.vel_ = new ::Shooter::PVector(*from._impl_.vel_);
  }
  // @@protoc_insertion_point(copy_constructor:Shooter.PMovement)
}

inline void PMovement::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.id_){nullptr}
    , decltype(_impl_.loc_){nullptr}
    , decltype(_impl_.rot_){nullptr}
    , decltype(_impl_.vel_){nullptr}
  };
}

PMovement::~PMovement() {
  // @@protoc_insertion_point(destructor:Shooter.PMovement)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PMovement::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.id_;
  if (this != internal_default_instance()) delete _impl_.loc_;
  if (this != internal_default_instance()) delete _impl_.rot_;
  if (this != internal_default_instance()) delete _impl_.vel_;
}

void PMovement::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PMovement::Clear() {
// @@protoc_insertion_point(message_clear_start:Shooter.PMovement)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.id_ != nullptr) {
    delete _impl_.id_;
  }
  _impl_.id_ = nullptr;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(_impl_.loc_ != nullptr);
      _impl_.loc_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(_impl_.rot_ != nullptr);
      _impl_.rot_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(_impl_.vel_ != nullptr);
      _impl_.vel_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PMovement::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Shooter.PClientId Id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_id(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .Shooter.PVector Loc = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_loc(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .Shooter.PRotator Rot = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_rot(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .Shooter.PVector Vel = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_vel(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PMovement::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Shooter.PMovement)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Shooter.PClientId Id = 1;
  if (this->_internal_has_id()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::id(this),
        _Internal::id(this).GetCachedSize(), target, stream);
  }

  // optional .Shooter.PVector Loc = 2;
  if (_internal_has_loc()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::loc(this),
        _Internal::loc(this).GetCachedSize(), target, stream);
  }

  // optional .Shooter.PRotator Rot = 3;
  if (_internal_has_rot()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::rot(this),
        _Internal::rot(this).GetCachedSize(), target, stream);
  }

  // optional .Shooter.PVector Vel = 4;
  if (_internal_has_vel()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::vel(this),
        _Internal::vel(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Shooter.PMovement)
  return target;
}

size_t PMovement::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Shooter.PMovement)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Shooter.PClientId Id = 1;
  if (this->_internal_has_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.id_);
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional .Shooter.PVector Loc = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.loc_);
    }

    // optional .Shooter.PRotator Rot = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.rot_);
    }

    // optional .Shooter.PVector Vel = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.vel_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PMovement::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PMovement::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PMovement::GetClassData() const { return &_class_data_; }


void PMovement::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PMovement*>(&to_msg);
  auto& from = static_cast<const PMovement&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Shooter.PMovement)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_id()) {
    _this->_internal_mutable_id()->::Shooter::PClientId::MergeFrom(
        from._internal_id());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_loc()->::Shooter::PVector::MergeFrom(
          from._internal_loc());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_rot()->::Shooter::PRotator::MergeFrom(
          from._internal_rot());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_mutable_vel()->::Shooter::PVector::MergeFrom(
          from._internal_vel());
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PMovement::CopyFrom(const PMovement& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Shooter.PMovement)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PMovement::IsInitialized() const {
  return true;
}

void PMovement::InternalSwap(PMovement* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PMovement, _impl_.vel_)
      + sizeof(PMovement::_impl_.vel_)
      - PROTOBUF_FIELD_OFFSET(PMovement, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PMovement::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ShooterProtocol_2eproto_getter, &descriptor_table_ShooterProtocol_2eproto_once,
      file_level_metadata_ShooterProtocol_2eproto[5]);
}

// ===================================================================

class PAnimState::_Internal {
 public:
  using HasBits = decltype(std::declval<PAnimState>()._impl_._has_bits_);
  static const ::Shooter::PClientId& id(const PAnimState* msg);
  static void set_has_aimyaw(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_aimpitch(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::Shooter::PClientId&
PAnimState::_Internal::id(const PAnimState* msg) {
  return *msg->_impl_.id_;
}
PAnimState::PAnimState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Shooter.PAnimState)
}
PAnimState::PAnimState(const PAnimState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PAnimState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.id_){nullptr}
    , decltype(_impl_.aimyaw_){}
    , decltype(_impl_.aimpitch_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_id()) {
    _this->_impl_.id_ = new ::Shooter::PClientId(*from._impl_.id_);
  }
  ::memcpy(&_impl_.aimyaw_, &from._impl_.aimyaw_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.aimpitch_) -
    reinterpret_cast<char*>(&_impl_.aimyaw_)) + sizeof(_impl_.aimpitch_));
  // @@protoc_insertion_point(copy_constructor:Shooter.PAnimState)
}

inline void PAnimState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.id_){nullptr}
    , decltype(_impl_.aimyaw_){0}
    , decltype(_impl_.aimpitch_){0}
  };
}

PAnimState::~PAnimState() {
  // @@protoc_insertion_point(destructor:Shooter.PAnimState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PAnimState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.id_;
}

void PAnimState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PAnimState::Clear() {
// @@protoc_insertion_point(message_clear_start:Shooter.PAnimState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.id_ != nullptr) {
    delete _impl_.id_;
  }
  _impl_.id_ = nullptr;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.aimyaw_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.aimpitch_) -
        reinterpret_cast<char*>(&_impl_.aimyaw_)) + sizeof(_impl_.aimpitch_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PAnimState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Shooter.PClientId Id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_id(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional float AimYaw = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _Internal::set_has_aimyaw(&has_bits);
          _impl_.aimyaw_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // optional float AimPitch = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _Internal::set_has_aimpitch(&has_bits);
          _impl_.aimpitch_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PAnimState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Shooter.PAnimState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Shooter.PClientId Id = 1;
  if (this->_internal_has_id()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::id(this),
        _Internal::id(this).GetCachedSize(), target, stream);
  }

  // optional float AimYaw = 2;
  if (_internal_has_aimyaw()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_aimyaw(), target);
  }

  // optional float AimPitch = 3;
  if (_internal_has_aimpitch()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_aimpitch(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Shooter.PAnimState)
  return target;
}

size_t PAnimState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Shooter.PAnimState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Shooter.PClientId Id = 1;
  if (this->_internal_has_id()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.id_);
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional float AimYaw = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 4;
    }

    // optional float AimPitch = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 4;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PAnimState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PAnimState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PAnimState::GetClassData() const { return &_class_data_; }


void PAnimState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PAnimState*>(&to_msg);
  auto& from = static_cast<const PAnimState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Shooter.PAnimState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_id()) {
    _this->_internal_mutable_id()->::Shooter::PClientId::MergeFrom(
        from._internal_id());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.aimyaw_ = from._impl_.aimyaw_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.aimpitch_ = from._impl_.aimpitch_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PAnimState::CopyFrom(const PAnimState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Shooter.PAnimState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PAnimState::IsInitialized() const {
  return true;
}

void PAnimState::InternalSwap(PAnimState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PAnimState, _impl_.aimpitch_)
      + sizeof(PAnimState::_impl_.aimpitch_)
      - PROTOBUF_FIELD_OFFSET(PAnimState, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PAnimState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ShooterProtocol_2eproto_getter, &descriptor_table_ShooterProtocol_2eproto_once,
      file_level_metadata_ShooterProtocol_2eproto[6]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Shooter
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Shooter::PVector*
Arena::CreateMaybeMessage< ::Shooter::PVector >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Shooter::PVector >(arena);
}
template<> PROTOBUF_NOINLINE ::Shooter::PRotator*
Arena::CreateMaybeMessage< ::Shooter::PRotator >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Shooter::PRotator >(arena);
}
template<> PROTOBUF_NOINLINE ::Shooter::PWeapon*
Arena::CreateMaybeMessage< ::Shooter::PWeapon >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Shooter::PWeapon >(arena);
}
template<> PROTOBUF_NOINLINE ::Shooter::PFireEvent*
Arena::CreateMaybeMessage< ::Shooter::PFireEvent >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Shooter::PFireEvent >(arena);
}
template<> PROTOBUF_NOINLINE ::Shooter::PClientId*
Arena::CreateMaybeMessage< ::Shooter::PClientId >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Shooter::PClientId >(arena);
}
template<> PROTOBUF_NOINLINE ::Shooter::PMovement*
Arena::CreateMaybeMessage< ::Shooter::PMovement >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Shooter::PMovement >(arena);
}
template<> PROTOBUF_NOINLINE ::Shooter::PAnimState*
Arena::CreateMaybeMessage< ::Shooter::PAnimState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Shooter::PAnimState >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
